# Generated by Django 4.2.9 on 2024-01-31 16:34

from django.db import migrations, models

import cars.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[cars.models.validate_year_range]),
        ),
    ]
