# Generated by Django 4.2.9 on 2024-01-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='client_id',
            new_name='client',
        ),
    ]
