# Generated by Django 4.2.9 on 2024-02-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear_type',
            field=models.SmallIntegerField(choices=[(0, 'bevel gears'), (1, 'worm gears'), (2, 'helical gears'), (3, 'rack and pinion gears'), (4, 'internal gears'), (5, 'straight bevel gears'), (6, 'spiral bevel gears'), (7, 'double helical gears'), (8, 'crown gears'), (9, 'herringbone gears'), (10, 'another type')], default=10),
        ),
    ]
