# Generated by Django 4.2.9 on 2024-02-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_alter_station_address'),
        ('workers', '0002_worker_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='service_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.station'),
        ),
    ]
