# Generated by Django 4.2.9 on 2024-02-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_service_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='service_station',
        ),
    ]
