# Generated by Django 4.2.9 on 2024-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountusers_remove_accountownerusers_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
