# Generated by Django 4.2.9 on 2024-01-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
