# Generated by Django 4.2.9 on 2024-02-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountusers'),
        ),
    ]
