# Generated by Django 4.2.9 on 2024-02-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_accountusers_options_emailverificationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerificationModel',
            new_name='EmailVerification',
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Email Verification Model', 'verbose_name_plural': 'Email Verification Models'},
        ),
    ]
