# Generated by Django 4.2.9 on 2024-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_rename_station_owner_station_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
