# Generated by Django 4.2.9 on 2024-02-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_station_address_alter_station_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('name', 'address')},
        ),
    ]
