# Generated by Django 4.2.9 on 2024-02-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_address_alter_station_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='station_owner',
            new_name='owner',
        ),
    ]
