# Generated by Django 4.2.9 on 2024-01-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_delete_adminuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountUsers',
            new_name='AccountOwnerUsers',
        ),
    ]
