# Generated by Django 4.2.9 on 2024-01-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountusers_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accountusers'),
        ),
    ]
