# Generated by Django 4.2.9 on 2024-01-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accountusers_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountusers',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='accountusers',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
