# Generated by Django 4.2.9 on 2024-01-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accountusers_owner_id_accountusers_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountusers',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
    ]
