# Generated by Django 4.2.9 on 2024-02-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_accountusers_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountusers',
            managers=[
            ],
        ),
    ]
