# Generated by Django 4.2.9 on 2024-02-15 08:52

from django.db import migrations

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_accountusers_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountusers',
            managers=[
                ('objects', accounts.models.AccountUsersManager()),
            ],
        ),
    ]
