# Generated by Django 4.2.9 on 2024-02-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_accountusers_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
