# Generated by Django 4.2.9 on 2024-02-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_emailverificationmodel_emailverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
