# Generated by Django 4.2.9 on 2024-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_accountusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountusers',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
