# Generated by Django 4.2.9 on 2024-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_accountusers_is_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
