# Generated by Django 4.2.9 on 2024-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_accountusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
