# Generated by Django 4.2.9 on 2024-03-06 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_accountusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusers',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10-digit number.', regex='^\\d{10}$')]),
        ),
    ]
