# Generated by Django 4.2.9 on 2024-01-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=8)),
                ('vin_number', models.CharField(max_length=17)),
                ('mark', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField(max_length=4)),
                ('engine', models.CharField(max_length=32)),
                ('gear_type', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=60)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
    ]
