# Generated by Django 5.2.16 on 2026-08-01 20:18

import cars.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=8)),
                ('vin_number', models.CharField(max_length=17)),
                ('mark', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(cars.models.current_year)])),
                ('engine', models.CharField(max_length=32)),
                ('gear_type', models.SmallIntegerField(choices=[(0, 'bevel gears'), (1, 'worm gears'), (2, 'helical gears'), (3, 'rack and pinion gears'), (4, 'internal gears'), (5, 'straight bevel gears'), (6, 'spiral bevel gears'), (7, 'double helical gears'), (8, 'crown gears'), (9, 'herringbone gears'), (10, 'another type')], default=10)),
                ('comment', models.TextField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
