# Generated by Django 4.2.9 on 2024-02-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_client_id_car_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
