# Generated by Django 4.2.9 on 2024-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_car_number_alter_car_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17),
        ),
    ]
