# Generated by Django 4.2.9 on 2024-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='comment',
            field=models.TextField(max_length=60),
        ),
    ]
