# Generated by Django 4.2.9 on 2024-02-06 11:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, 'not started'), (1, 'in progress'), (2, 'ready for pickup'), (3, 'car picked up')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 2, 6)),
        ),
    ]
