# Generated by Django 4.2.9 on 2024-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.TextField(default='repair', max_length=200),
        ),
    ]
