# Generated by Django 4.2.9 on 2024-02-06 11:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_process_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 11, 17, 13, 949538, tzinfo=datetime.timezone.utc)),
        ),
    ]
