# Generated by Django 4.2.9 on 2024-02-06 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
