# Generated by Django 4.2.9 on 2024-02-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('orders', '0005_alter_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.station'),
        ),
    ]
