# Generated by Django 4.2.9 on 2024-02-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        ('orders', '0006_order_service_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workers',
            field=models.ManyToManyField(through='workers.WorkerOrder', to='workers.worker'),
        ),
    ]
